apiVersion: v1
kind: Pod
metadata:
  namespace: autogpt
  annotations:
    kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: migrate
  name: migrate
spec:
  containers:
    - args:
        - sh
        - -c
        - poetry run prisma migrate deploy
      env:
        - name: DATABASE_URL
          value: postgresql://postgres:your-super-secret-and-long-postgres-password@db:5432/postgres?connect_timeout=60&schema=platform
      image: 582822331796.dkr.ecr.us-east-1.amazonaws.com/autogpt/platform/migrate:latest
      livenessProbe:
        exec:
          command:
            - poetry
            - run
            - prisma
            - migrate
            - status
        failureThreshold: 5
        periodSeconds: 10
        timeoutSeconds: 5
      name: migrate
  restartPolicy: OnFailure
