apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: autogpt
  annotations:
    kompose.version: 1.35.0
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.version: 1.35.04
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - image: 582822331796.dkr.ecr.us-east-1.amazonaws.com/autogpt/platform/frontend:latest
          #command: ["/bin/sh", "-c", "sleep infinity"] # poetry run app
          command: ["/bin/sh","-c","node server.js"]
          name: frontend
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: autogpt
  annotations:
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3000
  selector:
    io.kompose.service: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: autogpt
  annotations:
    kubernetes.io/ingress.class: alb
    # spec.ingressClassName: alb
    alb.ingress.kubernetes.io/scheme: internet-facing 
    alb.ingress.kubernetes.io/target-type: instance
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:582822331796:certificate/3f30d5a3-4e52-4ed9-a1e2-fe07c0c2dc99
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}, {"HTTPS":443}]'
    # alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=600
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=600
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '100'
    alb.ingress.kubernetes.io/load-balancer-name: autogpt-frontend
    # alb.ingress.kubernetes.io/group.name: ingressgroup-cta
    alb.ingress.kubernetes.io/rewrite-target: "/$1"
  labels:
    version: "1.001"
spec:
  defaultBackend:
    service:
      name: frontend
      port:
        number: 3100

