apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: autogpt
  annotations:
    kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: websocket-server
  name: websocket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: websocket-server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: websocket-server
    spec:
      containers:
        - args:
            - python
            - -m
            - backend.ws
          env:
            - name: BACKEND_CORS_ALLOW_ORIGINS
              value: '["http://localhost:3000"]'
            - name: DATABASE_URL
              value: postgresql://postgres:your-super-secret-and-long-postgres-password@db:5432/postgres?connect_timeout=60&schema=platform
            - name: ENABLE_AUTH
              value: "true"
            - name: PYRO_HOST
              value: 0.0.0.0
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PASSWORD
              value: password
            - name: REDIS_PORT
              value: "6379"
            - name: SUPABASE_JWT_SECRET
              value: your-super-secret-jwt-token-with-at-least-32-characters-long
          image: 582822331796.dkr.ecr.us-east-1.amazonaws.com/autogpt/platform/websocket:latest
          name: websocket-server
          ports:
            - containerPort: 8001
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: autogpt
  annotations:
    kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: websocket-server
  name: websocket-server
spec:
  ports:
    - name: "8001"
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: websocket-server
