apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: autogpt
  annotations:
    kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: analytics
  name: analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analytics
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: analytics
    spec:
      containers:
        - env:
            - name: DB_DATABASE
              value: postgres
            - name: DB_HOSTNAME
              value: db
            - name: DB_PASSWORD
              value: your-super-secret-and-long-postgres-password
            - name: DB_PORT
              value: "5432"
            - name: DB_SCHEMA
              value: _analytics
            - name: DB_USERNAME
              value: supabase_admin
            - name: LOGFLARE_API_KEY
              value: your-super-secret-and-long-logflare-key
            - name: LOGFLARE_FEATURE_FLAG_OVERRIDE
              value: multibackend=true
            - name: LOGFLARE_MIN_CLUSTER_SIZE
              value: "1"
            - name: LOGFLARE_NODE_HOST
              value: 127.0.0.1
            - name: LOGFLARE_SINGLE_TENANT
              value: "true"
            - name: LOGFLARE_SUPABASE_MODE
              value: "true"
            - name: POSTGRES_BACKEND_SCHEMA
              value: _analytics
            - name: POSTGRES_BACKEND_URL
              value: postgresql://supabase_admin:your-super-secret-and-long-postgres-password@db:5432/postgres
          image: 582822331796.dkr.ecr.us-east-1.amazonaws.com/autogpt/supbase/logflare:latest
          livenessProbe:
            exec:
              command:
                - curl
                - http://analytics:4000/health
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          name: supabase-analytics
          ports:
            - containerPort: 4000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: autogpt
  annotations:
    kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: analytics
  name: analytics
spec:
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
  selector:
    io.kompose.service: analytics
---
