apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: autogpt
  annotations:
    kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: vector
  name: vector
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: vector
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Amazon\AWSCLIV2\kompose.exe convert -v -f .\docker-compose.yml
        kompose.version: 1.35.05 (9532ceef3)
      labels:
        io.kompose.service: vector
    spec:
      containers:
        - args:
            - --config
            - etc/vector/config1/vector.yml
          env:
            - name: LOGFLARE_API_KEY
              value: your-super-secret-and-long-logflare-key
            - name: VECTOR_SELF_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: 582822331796.dkr.ecr.us-east-1.amazonaws.com/autogpt/supbase/vector:latest
          # livenessProbe:
          #   exec:
          #     command:
          #       - wget
          #       - --no-verbose
          #       - --tries=1
          #       - --spider
          #       - http://vector:9001/health
          #   failureThreshold: 3
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          # command: ["/bin/sh", "-c", "sleep infinity"]
          name: supabase-vector
          volumeMounts:
            - mountPath: /etc/vector/config1/
              name: vector-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: vector-claim0
          persistentVolumeClaim:
            claimName: vector-claim0
            readOnly: true
---

