/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { APIKeyStatus } from "./aPIKeyStatus";
import type { APIKeyPermission } from "./aPIKeyPermission";
import type { APIKeyInfoLastUsedAt } from "./aPIKeyInfoLastUsedAt";
import type { APIKeyInfoRevokedAt } from "./aPIKeyInfoRevokedAt";
import type { APIKeyInfoDescription } from "./aPIKeyInfoDescription";

export interface APIKeyInfo {
  id: string;
  name: string;
  /** The first 8 characters of the key */
  head: string;
  /** The last 8 characters of the key */
  tail: string;
  status: APIKeyStatus;
  permissions: APIKeyPermission[];
  created_at: Date;
  last_used_at?: APIKeyInfoLastUsedAt;
  revoked_at?: APIKeyInfoRevokedAt;
  description?: APIKeyInfoDescription;
  user_id: string;
}
