/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { CredentialsMetaResponseType } from "./credentialsMetaResponseType";
import type { CredentialsMetaResponseTitle } from "./credentialsMetaResponseTitle";
import type { CredentialsMetaResponseScopes } from "./credentialsMetaResponseScopes";
import type { CredentialsMetaResponseUsername } from "./credentialsMetaResponseUsername";
import type { CredentialsMetaResponseApiKey } from "./credentialsMetaResponseApiKey";
import type { CredentialsMetaResponseExpiresAt } from "./credentialsMetaResponseExpiresAt";
import type { CredentialsMetaResponseHost } from "./credentialsMetaResponseHost";

export interface CredentialsMetaResponse {
  id: string;
  provider: string;
  type: CredentialsMetaResponseType;
  title: CredentialsMetaResponseTitle;
  scopes: CredentialsMetaResponseScopes;
  username: CredentialsMetaResponseUsername;
  api_key: CredentialsMetaResponseApiKey;
  expires_at: CredentialsMetaResponseExpiresAt;
  /** Host pattern for host-scoped credentials */
  host?: CredentialsMetaResponseHost;
}
