/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * AutoGPT Agent Server
 * This server is used to execute agents that are created by the AutoGPT system.
 * OpenAPI spec version: 0.1
 */
import type { UserOnboardingUpdateCompletedSteps } from "./userOnboardingUpdateCompletedSteps";
import type { UserOnboardingUpdateWalletShown } from "./userOnboardingUpdateWalletShown";
import type { UserOnboardingUpdateNotified } from "./userOnboardingUpdateNotified";
import type { UserOnboardingUpdateUsageReason } from "./userOnboardingUpdateUsageReason";
import type { UserOnboardingUpdateIntegrations } from "./userOnboardingUpdateIntegrations";
import type { UserOnboardingUpdateOtherIntegrations } from "./userOnboardingUpdateOtherIntegrations";
import type { UserOnboardingUpdateSelectedStoreListingVersionId } from "./userOnboardingUpdateSelectedStoreListingVersionId";
import type { UserOnboardingUpdateAgentInput } from "./userOnboardingUpdateAgentInput";
import type { UserOnboardingUpdateOnboardingAgentExecutionId } from "./userOnboardingUpdateOnboardingAgentExecutionId";
import type { UserOnboardingUpdateAgentRuns } from "./userOnboardingUpdateAgentRuns";
import type { UserOnboardingUpdateLastRunAt } from "./userOnboardingUpdateLastRunAt";
import type { UserOnboardingUpdateConsecutiveRunDays } from "./userOnboardingUpdateConsecutiveRunDays";

export interface UserOnboardingUpdate {
  completedSteps?: UserOnboardingUpdateCompletedSteps;
  walletShown?: UserOnboardingUpdateWalletShown;
  notified?: UserOnboardingUpdateNotified;
  usageReason?: UserOnboardingUpdateUsageReason;
  integrations?: UserOnboardingUpdateIntegrations;
  otherIntegrations?: UserOnboardingUpdateOtherIntegrations;
  selectedStoreListingVersionId?: UserOnboardingUpdateSelectedStoreListingVersionId;
  agentInput?: UserOnboardingUpdateAgentInput;
  onboardingAgentExecutionId?: UserOnboardingUpdateOnboardingAgentExecutionId;
  agentRuns?: UserOnboardingUpdateAgentRuns;
  lastRunAt?: UserOnboardingUpdateLastRunAt;
  consecutiveRunDays?: UserOnboardingUpdateConsecutiveRunDays;
}
